### ISSUE TITLE
显示报错 网页无法登陆

### ISSUE THREAD

**Issue by 4682265664** [guoba-yunzai/guoba-plugin#12]
[报错.txt](https://github.com/guoba-yunzai/guoba-plugin/files/9566931/default.txt)
这是报错内容

**Comment by 4682265664** [comment]
我又 搞不懂了
![Uploading IMG_20220915_133109.jpg…]()

**Comment by sjlei** [comment]
你的图裂了

**Comment by 4682265664** [comment]
![IMG_20220915_133109](https://user-images.githubusercontent.com/36778791/190399600-ee0ae766-f4e8-4e81-ae6b-ea4094c0849f.png)

**Comment by 4682265664** [comment]
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::50831
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at Function.listen (C:\Users\蒋冬志\Desktop\Yunzai-Bot\node_modules\.pnpm\express@4.18.1\node_modules\express\lib\application.js:635:24)
    at createServer (file:///C:/Users/%E8%92%8B%E5%86%AC%E5%BF%97/Desktop/Yunzai-Bot/plugins/Guoba-Plugin/server/index.js?guoba-instance-version-1:29:20)
    at reload (file:///C:/Users/%E8%92%8B%E5%86%AC%E5%BF%97/Desktop/Yunzai-Bot/plugins/Guoba-Plugin/index.js:83:19)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1399:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 50831
}

这样吧 真麻烦 图片加载不全

**Comment by sjlei** [comment]
端口冲突，要么是后台没关干净有残留，重启电脑解决；要么是有其他应用占用端口，需要修改锅巴的端口
