### ISSUE TITLE
获取群列表失败

### ISSUE THREAD

**Issue by ikenxuan** [guoba-yunzai/guoba-plugin#70]
锅巴版本：https://github.com/guoba-yunzai/guoba-plugin/commit/c6ed065722669a81e062534b2dbdf3f5e3f9864e
云崽：trss-yunzai
适配器：icqq

## 遇到的问题
对应的guoba.support.js文件：[guoba.support.js](https://github.com/ikenxuan/kkkkkk-10086/blob/fa88c6db4dfb7a1761a0d05ef422428ca0aef173/guoba.support.js#L172)
无法获取群列表，前端点击对应元素时
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/112480306/94cd1356-df19-4f96-af62-5fa0142eca1f)

错误日志：
```bash
2|TRSS-Yunzai  | TypeError: .for is not iterable
2|TRSS-Yunzai  |     at OicqController.queryGroupList (file:///root/TRSS-Yunzai/plugins/Guoba-Plugin/server/controller/biz/OicqController.js?1715656811681:73:21)
2|TRSS-Yunzai  |     at Object.proceed (file:///root/TRSS-Yunzai/plugins/Guoba-Plugin/framework/src/core/RestController.js:76:38)
2|TRSS-Yunzai  |     at file:///root/TRSS-Yunzai/plugins/Guoba-Plugin/framework/src/core/RestController.js:112:28
2|TRSS-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2|TRSS-Yunzai  | TypeError: .for is not iterable
2|TRSS-Yunzai  |     at OicqController.queryGroupList (file:///root/TRSS-Yunzai/plugins/Guoba-Plugin/server/controller/biz/OicqController.js?1715656811681:73:21)
2|TRSS-Yunzai  |     at Object.proceed (file:///root/TRSS-Yunzai/plugins/Guoba-Plugin/framework/src/core/RestController.js:76:38)
2|TRSS-Yunzai  |     at file:///root/TRSS-Yunzai/plugins/Guoba-Plugin/framework/src/core/RestController.js:112:28
2|TRSS-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## 希望得到的
子表单中可以获取群列表

**Comment by ikenxuan** [comment]
另外在喵崽中，是可以正常获取到群列表，但是当将子表单的弹窗关闭后再次打开（情景：添加完一个推送用户后保存返回，然后再次点击添加，子表单弹窗出现，此时获取群列表为空白），获取群列表的功能似乎也失效了

**Comment by rainbowwarmth** [comment]
@ikenxuan 请使用这个版本https://gitee.com/rainbowwarmth/guoba-plugin
